"""add auth0_user_id to user model

Revision ID: 7ae87c006003
Revises: a96b03e13043
Create Date: 2025-07-06 22:08:37.524320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae87c006003'
down_revision: Union[str, None] = 'a96b03e13043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth0_user_id', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_user_auth0_user_id'), 'user', ['auth0_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_auth0_user_id'), table_name='user')
    op.drop_column('user', 'auth0_user_id')
    # ### end Alembic commands ###
