"""add account model and multi-account user support

Revision ID: f2e4da3c98b2
Revises: 7ae87c006003
Create Date: 2025-07-07 21:17:56.742140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e4da3c98b2'
down_revision: Union[str, None] = '7ae87c006003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_account_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_id'), 'account', ['id'], unique=False)
    op.create_index(op.f('ix_account_provider'), 'account', ['provider'], unique=False)
    op.create_index(op.f('ix_account_provider_account_id'), 'account', ['provider_account_id'], unique=False)
    op.create_index(op.f('ix_account_user_id'), 'account', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_auth0_user_id'), table_name='user')
    op.drop_column('user', 'auth0_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth0_user_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_user_auth0_user_id'), 'user', ['auth0_user_id'], unique=True)
    op.drop_index(op.f('ix_account_user_id'), table_name='account')
    op.drop_index(op.f('ix_account_provider_account_id'), table_name='account')
    op.drop_index(op.f('ix_account_provider'), table_name='account')
    op.drop_index(op.f('ix_account_id'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
